### ISSUE TITLE
The facebook-php-sdk is deprecated

### ISSUE THREAD

**Issue by abdielcs** [armetiz/ArmetizFacebookBundle#3]
The facebook-php-sdk is deprecated. Will be usefull update the bundle to the new facebook-php-sdk-v4 in https://github.com/facebook/facebook-php-sdk-v4

**Comment by armetiz** [comment]
Hi @abdielcs,
I'm sorry, but this bundle is not maintained anymore.

Feel free to make a fork ;)

Regards
